name = "TheGeneralizedSBM"
uuid = "181058b3-c81e-4cf0-9c95-a315177d34f6"
authors = ["Oriol Colomes"]
version = "0.0.1"

[compat]
julia = "1.11.1"
DrWatson = "2.19.0"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
